apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - name: nginx
        image: nginx:1.23.0
        resources:
          limits:
            memory: "25Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-volume
            mountPath: /usr/share/nginx/html
      initContainers:
      - name: copy-html
        image: nginx:1.23.0
        command: ["sh", "-c", "curl https://raw.githubusercontent.com/NAVRockClimber/k8s_training/main/Demo_4/index.html -o /usr/share/nginx/html/index.html"]
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: nginx-volume
      volumes:
        - name: nginx-volume
          persistentVolumeClaim:
            claimName: nginx
