apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
  - ingress.yaml
  - pvc.yaml
  - configmap.yaml

namespace: my-nginx

commonLabels:
  app: my-nginx-app

images:
- name: nginx
  newName: public.ecr.aws/nginx/nginx
  newTag: 1.23.0

patchesJson6902:
- target:
    version: v1 # apiVersion
    kind: Deployment
    name: nginx-deployment
  path: nginx-deployment-patch.yaml