apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx
  namespace: nginx
spec:
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce